name: Build GIBD Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            artifact_name: GIBD-linux.tar.gz
          - os: macos-latest
            platform: mac
            artifact_name: GIBD-mac.tar.gz
          - os: windows-latest
            platform: windows
            artifact_name: GIBD-windows.zip

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller pillow

    - name: Build executable
      run: |
        python build_executable.py ${{ matrix.platform }}

    - name: Verify executable
      shell: bash
      run: |
        if [ "${{ matrix.platform }}" = "windows" ]; then
          ls -la dist/${{ matrix.platform }}/GIBD.exe
          file dist/${{ matrix.platform }}/GIBD.exe || true
        else
          ls -la dist/${{ matrix.platform }}/GIBD
          file dist/${{ matrix.platform }}/GIBD || true
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: GIBD-${{ matrix.platform }}
        path: ${{ matrix.artifact_name }}
        retention-days: 30

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Display structure
      run: find artifacts -type f

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/GIBD-linux/GIBD-linux.tar.gz
          artifacts/GIBD-mac/GIBD-mac.tar.gz
          artifacts/GIBD-windows/GIBD-windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
